# Coin Price configuration

app:
  name: Coin Price indicator
  description: Coin Price is a crypto curency price indicator applet for Ubuntu
  url: https://github.com/nilgradisnik/coinprice-indicator
  version: "0.3.0"

author:
  name: Nil Gradisnik
  email: nil.gradisnik@gmail.com
  copyright: Copyright (C) 2014 Nil Gradisnik

artist:
  name: Alicen Maniscalco
  email: alicenfm@gmail.com
