# Coin Price configuration

app:
  name: Coin Price Indicator
  description: A cryptocurrency price ticker applet for Ubuntu
  url: https://github.com/nilgradisnik/coinprice-indicator
  version: "0.6.4"

authors:
  -
    name: Nil Gradisnik
    email: nil.gradisnik@gmail.com
  -
    name: Sander Van de Moortel
    email: sander.vandemoortel@gmail.com

contributors:
  -
    name: Nil Gradisnik
    email: nil.gradisnik@gmail.com
  -
    name: Sander Van de Moortel
    email: sander.vandemoortel@gmail.com
  -
    name: rick
    email: rick@anteaterllc.com
  -
    name: wizzard94
    email: wizzard94@github.com
  -
    name: Eliezer Aquino
    email: eliezer.aquino@gmail.com

artist:
  name: Alicen Maniscalco
  email: alicenfm@gmail.com
